[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
allow_paths = ['../aurora-sdk/aurora-solidity-sdk']
solc = "0.8.17"
optimizer = true
optimizer-runs = 10_000_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
